/**
 * Visualization Constants
 *
 * Constants for 3D visualization components
 */

export const VISUALIZATION_CONSTANTS = {
  // Tendon visualization
  TENDON_ACTIVATION_THRESHOLD: 0.001,

  // Sphere geometry
  SPHERE_RADIUS: 0.002,
  SPHERE_SEGMENTS: 8,
  SPHERE_RINGS: 6,

  // Clickable sphere multipliers
  CLICKABLE_SPHERE_SEGMENT_MULTIPLIER: 0.3,
  CLICKABLE_SPHERE_COUPLING_MULTIPLIER: 0.3,
  CLICKABLE_SPHERE_SEGMENTS: 6,
  CLICKABLE_SPHERE_RINGS: 4,

  // Camera settings
  CAMERA_POSITION: 1.5,
  CAMERA_DISTANCE: 200,
  CAMERA_NEAR: 0.5,
  CAMERA_FAR: 50,
  CAMERA_DISTANCE_MULTIPLIER: 1.5,
  CAMERA_MIN_MULTIPLIER: 0.5,
  CAMERA_MAX_MULTIPLIER: 4,
  CAMERA_MIN_DISTANCE: 50,
  CAMERA_MAX_DISTANCE: 1000,
  CAMERA_FAR_MULTIPLIER: 15,

  // Lighting
  LIGHT_INTENSITY: 15,
  LIGHT_DISTANCE: 200,
  LIGHT_POSITION_Z: 200,
} as const;
